version: '3'
services:
    bootstrap:
        build: './Docker/node'
        volumes:
            - ./:/app
        command: sh /start.sh
    php:
        build: './Docker/php'
        depends_on:
            - bootstrap
        networks:
            - backend
        volumes:
            - ./:/var/www/html/
        command: sh /start.sh
    apache:
        build: './Docker/apache'
        depends_on:
            - bootstrap
            - php
            - mysql
        networks:
            - frontend
            - backend
        ports:
            - '8080:80'
        volumes:
            - ./:/var/www/html/
    mysql:
        image: mysql:8.0.23
        depends_on:
            - bootstrap
        networks:
            - backend
        environment:
            - MYSQL_TCP_PORT=3306
            - MYSQL_DATABASE=camagru
            - MYSQL_USER=camagrusql
            - MYSQL_PASSWORD=password
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - ./Docker/mysql/migrate.sql:/docker-entrypoint-initdb.d/migrate.sql
            - ./Docker/mysql/seed.sql:/docker-entrypoint-initdb.d/seed.sql
            - persistent:/var/lib/mysql
    adminer:
        image: adminer:4.8.0-standalone
        depends_on:
            - bootstrap
            - php
            - mysql
        networks:
            - frontend
            - backend
        ports:
            - '8088:8080'
networks:
    frontend:
    backend:
volumes:
    persistent:
